### ISSUE TITLE
Project 1

### ISSUE THREAD

**Issue by nastyamalka** [sandcage/sandcage-api-python#2]
m=1
z=0
n=0
while m<354295:
    q=0
    z=0
    m+=1
    y=str(m)
    l=len(y)
    for n in range(l):
       q=int(y[n])**5
       z=z+q
    if m==z:
      print (m)

**Comment by sandcage** [comment]
I think you may have posted this in the wrong repository. Were you trying to add it to your first repo at https://github.com/nastyamalka/first-project ?

**Comment by nastyamalka** [comment]
I think so too, but I can`t fix it. When I was made pull requests it was a
trouble message "This branch has conflicts that must be resolved"
And that`s the problem. I`m new in GitHub and such platforms. I need to
share my code program by this GitHub, and I don`t know how. Can you help me?

2016-11-03 12:55 GMT+02:00 SandCage notifications@github.com:

**Comment by nastyamalka** [comment]
What?

2016-11-03 18:33 GMT+02:00 SandCage notifications@github.com:

**Comment by sandcage** [comment]
Given that this issues was not the intended repository and is not an issue with the SandCage python library, I have closed this issue.
