### ISSUE TITLE
Error  16-11-03_01

### ISSUE THREAD

**Issue by clapsmr** [sandcage/sandcage-api-python#3]
En este video muestro una pequeña incoherencia, si hago una búsqueda por un número de documento por ejemplo 12345, me trae todos los registros donde aparece ese número como parte de la identidad (eso está bien, hace un like). 
El tema es que si luego presiono en nuevo formulario y me agrega uno, sin considerar el número que se digitó. Hay que solucionarlo  porque me tiene que dar para ingresar uno nuevo, pero del que digité y también tener en cuenta el número de las gestas del número que realmente digite y no de los que encontraron.

https://drive.google.com/open?id=0Bw5YUxaMbLXWZTVkWEF5Y2p4NDg

**Comment by sandcage** [comment]
I think you are posting this issues in the wrong repository. The information you have provided is inconsistence with the SandCage python library and/or SandCage API.

**Comment by sandcage** [comment]
If you are interfacing with SandCage, please send us a message at contact@sandcage.com with the email address linked with your SandCage account.
