### ISSUE TITLE
error 161103_02

### ISSUE THREAD

**Issue by clapsmr** [sandcage/sandcage-api-python#4]
Las fechas no sé si están considerándose en las validaciones..

![image](https://cloud.githubusercontent.com/assets/17830940/19966330/0e45e204-a1aa-11e6-8e8c-6f93fa86937a.png)

**Comment by sandcage** [comment]
I think you are posting this issues in the wrong repository. The information you have provided is inconsistence with the SandCage python library and/or SandCage API.

**Comment by sandcage** [comment]
If you are interfacing with SandCage, please send us a message at contact@sandcage.com with the email address linked with your SandCage account.
