### ISSUE TITLE
error 161103_03

### ISSUE THREAD

**Issue by clapsmr** [sandcage/sandcage-api-python#5]
Estoy pensando que una forma de validar las fechas  (excepto las de nacimiento de la madre, etc.)  podría ser el año actual (+)(-) 1, para que no ocurra lo de la imagen..
En la misma imagen el grupo sanguíneo está en minúscula y también permite mayúscula (esto es para considerar) no se si luego no dará problemas este tipo de cosas.. Tal vez en el ingreso cuando pierde el foco podría poner todo en mayúsculas..

![image](https://cloud.githubusercontent.com/assets/17830940/19966409/759e54b8-a1aa-11e6-8a79-dae7c878eea0.png)

**Comment by sandcage** [comment]
I think you are posting this issues in the wrong repository. The information you have provided is inconsistence with the SandCage python library and/or SandCage API.

**Comment by sandcage** [comment]
If you are interfacing with SandCage, please send us a message at contact@sandcage.com with the email address linked with your SandCage account.

**Comment by clapsmr** [comment]
sorry. I am trying to delete it.
